# Generated by Django 5.1.6 on 2025-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0003_treeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('co2_reduction', models.CharField(max_length=50)),
            ],
        ),
    ]
