# Generated by Django 5.1.6 on 2025-04-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0006_alter_order_options_alter_order_items_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='societyapp.order')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societyapp.product')),
            ],
        ),
    ]
