# Generated by Django 5.1.6 on 2025-04-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0007_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='tree',
            new_name='product',
        ),
    ]
