# Generated by Django 5.1.6 on 2025-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0008_rename_tree_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
