# Generated by Django 5.1.6 on 2025-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0010_remove_blogpost_summary_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
