# Generated by Django 5.1.6 on 2025-04-20 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0011_alter_blogpost_options_remove_blogpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_markdown',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbs/'),
        ),
    ]
