# Generated by Django 5.1.6 on 2025-04-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0013_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='donation_proofs/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
