# Generated by Django 5.1.6 on 2025-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0014_donation_proof_alter_donation_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us - Green Future Society', max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
