# Generated by Django 5.1.6 on 2025-06-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0017_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
    ]
