# Generated by Django 5.1.6 on 2025-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0018_rename_events_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
