# Generated by Django 5.2.7 on 2025-10-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0020_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
